### ISSUE TITLE
KiCad or Gerber files available?

### ISSUE THREAD

**Issue by careyer** [akari-tun/iAts_pro#1]
Hi there,

this looks like awesome project and I am considering putting some of my ESP32 sitting on the shelf to good use. Do you think it is possible to share design files of the PCB (Gerbers or KiCad or anything that allows to order a small number of those boards with a PCB manufacturer)? 

Thank you very much in advance!
Best regards!
Thomas

**Comment by akari-tun** [comment]
I am glad you are interested in my project. This project is still development on the way,So the PCB is also in continuous improvement.You can give me your e-mail here, and I will send you the Gerber file of the last version.

**Comment by careyer** [comment]
Hi TanJun, thank you for coming back to me! Your friend DusKing was kind enough to contact me via Telegram and offered to forward my email address to you so I don't have to publish it in public (you know... bots, spam and all sorts of nasty stuff  ;-). I think he will reach out to you the next days and give you my email. Are you on Telegram as well?

Best regards and keep that great project going.

P.S: I have browsed the repository or your arduino based tracker just yesterday and it is so well documneted! That is really awesome. I was just struggling a bit with the chinese fonts. Happy to see that you do this one in english language.

**Comment by akari-tun** [comment]
Hi Thomas, DusKing was gave me your email address at last night, I send the files of this project to you just now. I written few documents for this project in Chinese language, and so sorry for I don't have enough time to write documents in English recently. If you need anything other,please tell me.

Before you provide the Gerber files to the manufacturer, you must check the Bom of V2.2 and make sure all components can easy to buy. I used an old second-hand power module "FPDK12SR8003PSVP".

![123](https://user-images.githubusercontent.com/37833149/65007124-bbe0a080-d937-11e9-9372-146dfcc87eda.png)

I bought this module easily and cheaply on www.taobao.com, I don't know if you can easily to buy this module. I plan to replace this module with "MP9447", which is a good power IC, but it a little expensive.

I haven't used Telegram app so I'm sorry I don't have Telegram Account  :-(

**Comment by careyer** [comment]
Oh wow! Thanks! ... Your word of warning is much appreciated. Indeed the FPDK12SR8003PSVP can not be purchased anywhere here. From what I can tell it is long EOL. I could not find the "MP9443" either though (just a Yamaha Termosensor that is called exactly like this ;-).
Maybe consider a readily avialable part here. I think what you need is a DC-DC converter right?
So I better wait for the final version then so that we stay compatible and can share test results.
Many thanks in advance and keep that awesome project going!

**Comment by akari-tun** [comment]
Oh sorry, I wrote a wrong word! It's "MP9447" , A DC-DC converter IC. It can provide 5A current, I think can adapter most of the sevro requirements . 
I will modify it as soon as possible and other components can you easily to buy?

**Comment by careyer** [comment]
Alright! Now MP9447 looks much better suited for the job ;-). I can source this here no problem. However It looks like a BGA package design, is it?  I think for the ease of use and to enable more people to rercreate this design it would be better to choose "ordinary" ICs with legs - they just solder so much easier. 
Other than that I skimmed through the BOM and found the CP2102-GMR to be also BGA design, is it? The RT9013-33GB seems to be availible only in China as well. There is no way in getting it from a distributor nearby.  
All other parts should not give any problems and are readily availible. 

Best regards! Have a good day.
Thomas

**Comment by akari-tun** [comment]
I think MP9447 and CP2102 belong to QFN package, but it is impossible to solder with soldering iron.
I recommend soldering with solder paste, appropriate amount of solder paste and melting it with a heat gun.

The CP2102 is not required,I brought out UART0 with 2.54mm pin and download program through an external USB to TTL module, but it's not too convenient to use, so I Integrated it in board.

If the RT9013-33GB can't buy easily then I need to choose a new 3.3v LDO IC.I think most of MPS's products can easily to buy from all of the world？

Thanks for your wishes and you have a good day too.
