### ISSUE TITLE
程序结构写的很好，里面有大量结构体和指针，怎样理清代码结构，尤其是UI部分

### ISSUE THREAD

**Issue by cgrrty** [akari-tun/iAts_pro#3]
程序结构写的很好，里面有大量结构体和指针，怎样理清代码结构，尤其是UI部分。另外wifi部分，业务处理代码在哪里实现的？谢谢😜

**Comment by akari-tun** [comment]
第一次用C语言写程序，经验不足，很多逻辑处理得不是太好，导致BUG比较多，业务部分的代码主要在tracker文件夹，UI部分的代码都在ui文件夹。
